# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ALSU KURR
email: k.alsu@me.com
description: > # this means to ignore newlines until "baseurl:"
  FRONT END DEVELOPER AND DESIGNER
baseurl: "" # the subpath of your site, e.g. /blog
url: "alsukurr.com" # the base hostname & protocol for your site
twitter_username: alsukurr
github_username:  alsukurr

# Build settings
markdown: kramdown
subtitle-quote: "It is not that I'm so smart. But I stay with the questions much longer."
subtitle-author: "Albert Einstein"

# gems: [jekyll-paginate]
# paginate: 2 # number of posts you want per page
# paginate_path: "/blog/page/:num"

collections:
  - my_work
  - taxi_work_collection
  - mirum_work_collection


exclude: ["node_modules", "gulpfile.js", "package.json"]